# Generated by Django 3.2.5 on 2021-07-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_pessoa_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='cargo',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cargo',
            field=models.ManyToManyField(to='autenticacao.Cargos'),
        ),
    ]
