# Generated by Django 3.2.5 on 2021-08-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_auto_20210721_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
