# Generated by Django 3.2.5 on 2021-08-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0006_auto_20210803_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='pedidos',
            field=models.ManyToManyField(to='autenticacao.Pedido'),
        ),
    ]
